service: [name me with a single word]
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
#  region: us-west-1
  environment:
# to lock your Lambda to your Alexa Skill
#    APP_ID: amzn1.ask.skill.nnnnnnnn-nnnn-nnnn-nnnn-nnnnnnnnnnnn
# permissions for persisting session data
#   USE_DYNAMO_DB: true
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "dynamodb:DescribeTable"
#        - "dynamodb:Query"
#        - "dynamodb:Scan"
#        - "dynamodb:GetItem"
#        - "dynamodb:PutItem"
#        - "dynamodb:UpdateItem"
#        - "dynamodb:DeleteItem"
#        - "dynamodb:CreateTable"
#      Resource: "arn:aws:dynamodb:eu-west-1:*:*"
functions:
  hello:
    handler: lambda/custom/index.handler
    events:
      - alexaSkill
package:
  include:
    - index.js
    - node_modules/alexa-sdk/**
    - node_modules/i18next/**
    - node_modules/i18next-sprintf-postprocessor/**
  exclude:
    - node_modules/**
    - .*/**
